/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/reissue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ?��?��?�� ?��?�� ?��발급
         * @description 리프?��?�� ?��?��?�� ?��?��?��?�� ?��로운 ?��?��?�� ?��?��?�� 발급받습?��?��. 리프?��?�� ?��?��?? 쿠키?��?�� ?��?��?���? ?��?��?��?��?��.
         */
        post: operations["reissue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ?��?���??��
         * @description ?��로운 ?��?��?�� ?��록합?��?��. ?���? ?�� ?��?��?���? 로그?��?��?�� JWT ?��?��?�� ?��?���? 리프?��?�� ?��?��(쿠키)?�� 반환?��?��?��.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그?��?��
         * @description ?��?�� ?��?��?���? 로그?��?�� 처리?���? 리프?��?�� ?��?��?�� 무효?��?��?��?��. 리프?��?�� ?��?��?? 쿠키?��?�� ?��?��?���? ?��?��?��?��?��.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그?��
         * @description ?��메일�? 비�?번호�? 로그?��?��?��?��. ?���? ?�� JWT ?��?��?�� ?��?���? 리프?��?�� ?��?��(쿠키)?�� 반환?��?��?��.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * �?측�? 조회
         * @description �??��?�� ?��치�? 반경 ?��?�� �? �?측�?�? 조회?��?��?��. ?���? ?��?�� ?��?�� �??��?��?��?��.
         */
        get: operations["getObservationSpots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ?�� ?���? 조회
         * @description ?��?�� 로그?��?�� ?��?��?��?�� ?��보�?? 조회?��?��?��. JWT ?��?�� ?��증이 ?��?��?��?��?��.
         */
        get: operations["getMyInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/exists/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ?��메일 중복 �?�?
         * @description ?��?���??�� ?�� ?��메일 중복 ?���?�? ?��?��?��?��?��. ?���? ?��?�� ?��?�� �??��?��?��?��.
         */
        get: operations["validateEmailDuplicated"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * �? �?�? ?���? 조회
         * @description �??��?�� ?��치의 ?��?�� 며칠간의 �? �?�? ?��보�?? 조회?��?��?��. ?��짜별, ?��간�?별로 ?��?��?�� �?�? 조건 ?��?��?? ?��보�?? ?��공합?��?��. ?���? ?��?�� ?��?�� �??��?��?��?��.
         */
        get: operations["getForecast"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * �? �?�? 조건 분석
         * @description �??��?�� ?���?, ?���?, ?��간의 �? �?�? 조건?�� 종합?��?���? 분석?��?��?��. 기상 ?���?, 천문 ?���?, 광해 ?��보�?? ?��?��?�� ?��?�� 분석 결과�? ?��공합?��?��. ?���? ?��?�� ?��?�� �??��?��?��?��.
         */
        get: operations["analyzeStargazingCondition"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description ?���? ?��?�� ?��?�� DTO */
        AuthTokenResponse: {
            /**
             * @description JWT ?��?��?�� ?��?��
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            accessToken?: string;
        };
        /** @description ?��?���??�� ?���? ?���? */
        RegisterRequest: {
            /**
             * @description ?��메일 주소
             * @example user@example.com
             */
            email: string;
            /**
             * @description 비�?번호
             * @example password123
             */
            password: string;
            /**
             * @description ?��?��?��
             * @example 별보?���??��
             */
            nickname: string;
        };
        /** @description 로그?�� ?���? ?���? */
        LoginRequest: {
            /**
             * @description ?��메일 주소
             * @example user@example.com
             */
            email: string;
            /**
             * @description 비�?번호
             * @example password123
             */
            password: string;
        };
        /** @description �?측�? 조회 ?���? DTO */
        ObservationSpotRequest: {
            /**
             * Format: double
             * @description ?��?��
             * @example 37.5665
             */
            lat: number;
            /**
             * Format: double
             * @description 경도
             * @example 126.978
             */
            lon: number;
            /**
             * Format: int32
             * @description �??�� 반경 (km)
             * @example 50
             */
            radius: number;
        };
        /** @description �?측�? ?���? ?��?�� DTO */
        ObservationSpotResponse: {
            /**
             * Format: int64
             * @description �?측�? ID
             * @example 1
             */
            id?: number;
            /**
             * @description �?측�? ?���?
             * @example 강원?�� ?��창군 ??�??��
             */
            title?: string;
            /**
             * @description 주소
             * @example 강원?�� ?��창군 ??�??���?
             */
            address?: string;
            /**
             * Format: double
             * @description ?��?��
             * @example 37.5665
             */
            latitude?: number;
            /**
             * Format: double
             * @description 경도
             * @example 126.978
             */
            longitude?: number;
            /**
             * @description �?측�? ?���?
             * @example 별이 ?�� 보이?�� 명소?��?��?��.
             */
            description?: string;
            /**
             * Format: int32
             * @description 보�? ?���? (1-9, ?��?��?���? 좋음)
             * @example 3
             */
            bortleScale?: number;
            /**
             * @description 주차 �??�� ?���?
             * @example true
             */
            isParkingAvailable?: boolean;
            /**
             * @description ?��?��?�� ?��?�� �??�� ?���?
             * @example true
             */
            isRestroomAvailable?: boolean;
            /**
             * @description 차량 ?���? �??�� ?���?
             * @example true
             */
            isCarAccess?: boolean;
            /**
             * @description ?��?��?�� ?��미�? URL
             * @example https://example.com/image.jpg
             */
            thumbnailImage?: string;
        };
        /** @description ?��?�� ?���? ?��?�� DTO */
        MemberInfoResponse: {
            /**
             * Format: int64
             * @description ?��?�� ID
             * @example 1
             */
            memberId?: number;
            /**
             * @description ?��?��?��
             * @example 별보?���??��
             */
            nickname?: string;
        };
        /** @description ?��메일 중복 �?�? ?��?�� DTO */
        MemberValidationResponse: {
            /**
             * @description �?�? 결과 (true: ?��?�� �??��, false: 중복?��)
             * @example true
             */
            validated?: boolean;
        };
        /**
         * @description �?�? ?���? (HH:mm ?��?��)
         * @example 22:00
         */
        LocalTime: {
            /** Format: int32 */
            hour?: number;
            /** Format: int32 */
            minute?: number;
            /** Format: int32 */
            second?: number;
            /** Format: int32 */
            nano?: number;
        };
        /** @description �? �?�? 조건 분석 ?���? DTO */
        StargazingRequest: {
            /**
             * Format: double
             * @description ?��?��
             * @example 37.5665
             */
            lat: number;
            /**
             * Format: double
             * @description 경도
             * @example 126.978
             */
            lon: number;
            /**
             * Format: date
             * @description �?�? ?���? (yyyy-MM-dd ?��?��)
             * @example 2025-12-25
             */
            date: string;
            time: components["schemas"]["LocalTime"];
        };
        /** @description ?���? ?���? */
        DailyForecast: {
            /**
             * @description ?���? (?��?�� ?��?��)
             * @example 2025-05-20 (�?)
             */
            date?: string;
            /**
             * @description ?���? ?���?
             * @example 07:00
             */
            sunrise?: string;
            /**
             * @description ?���? ?���?
             * @example 18:00
             */
            sunset?: string;
            /**
             * @description ?���? ?���?
             * @example 08:00
             */
            moonrise?: string;
            /**
             * @description ?���? ?���?
             * @example 20:00
             */
            moonset?: string;
            /** @description ?��간�?�? ?���? 목록 */
            hourlyForecasts?: components["schemas"]["HourlyForecast"][];
        };
        /** @description ?��간�?�? ?���? */
        HourlyForecast: {
            /**
             * @description ?���?
             * @example 21:00
             */
            time?: string;
            /**
             * Format: int32
             * @description �?�? ?��?�� (0-100)
             * @example 85
             */
            score?: number;
            /**
             * @description 감점 ?��?�� 목록
             * @example [
             *       "구름?��?�� 많음"
             *     ]
             */
            reasons?: string[];
            /**
             * @description �? ?���?
             * @example 4.5?���?
             */
            starGrade?: string;
            /**
             * Format: int32
             * @description 구름?�� (%)
             * @example 20
             */
            cloudCover?: number;
            /**
             * @description ?�� ?��?��
             * @example 초승?��
             */
            moonPhase?: string;
        };
        /** @description �? �?�? ?���? ?��?�� DTO */
        StargazingForecastResponse: {
            /** @description ?��짜별 ?���? 목록 */
            dailyForecasts?: components["schemas"]["DailyForecast"][];
        };
        /** @description 천문 ?���? */
        AstronomyInfo: {
            /**
             * @description ?�� ?��?��
             * @example 초승?��
             */
            moonPhase?: string;
            /**
             * @description ?���? ?���?
             * @example 07:00
             */
            sunrise?: string;
            /**
             * @description ?���? ?���?
             * @example 18:00
             */
            sunset?: string;
            /**
             * @description ?���? ?���?
             * @example 08:00
             */
            moonrise?: string;
            /**
             * @description ?���? ?���?
             * @example 20:00
             */
            moonset?: string;
        };
        /** @description 광해 ?���? */
        LightPollutionInfo: {
            /**
             * @description 보�? ?���? ?��?��?��
             * @example Class 3
             */
            bortleClass?: string;
            /**
             * @description 밝기 ?���?
             * @example ?��?��
             */
            brightness?: string;
            /**
             * @description ?���? ?���?
             * @example 6?���?
             */
            limitingMag?: string;
        };
        /** @description �? �?�? 조건 분석 ?��?�� DTO */
        StargazingAnalyzeResponse: {
            /**
             * @description �?�? ?���?
             * @example 2025-12-19
             */
            date?: string;
            /**
             * @description �?�? ?���?
             * @example 22:00
             */
            time?: string;
            /**
             * Format: int32
             * @description 종합 ?��?�� (0-100)
             * @example 85
             */
            totalScore?: number;
            /**
             * @description ?��?�� 감점 ?��?�� 목록
             * @example [
             *       "구름?��?�� 많음",
             *       "?��?���? ?��?��"
             *     ]
             */
            reasons?: string[];
            /**
             * @description AI ?���? ?��
             * @example ?��?�� �? �? �?측하�? 좋�? ?��?��?��?��?��!
             */
            aiComment?: string;
            weather?: components["schemas"]["WeatherInfo"];
            astronomy?: components["schemas"]["AstronomyInfo"];
            lightPollution?: components["schemas"]["LightPollutionInfo"];
        };
        /** @description 기상 ?���? */
        WeatherInfo: {
            /**
             * Format: int32
             * @description 구름?�� (%)
             * @example 20
             */
            cloudIndex?: number;
            /**
             * Format: int32
             * @description ?��?�� (%)
             * @example 60
             */
            humidityIndex?: number;
            /**
             * @description �??��?�� ?���?
             * @example 매우 좋음
             */
            visibilityText?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    reissue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ?��?�� ?��발급 ?���? */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthTokenResponse"];
                };
            };
            /** @description ?���? ?��?�� (리프?��?�� ?��?��?�� ?��?��?���? ?��거나 만료?��) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthTokenResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description ?��?���??�� ?���? */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthTokenResponse"];
                };
            };
            /** @description ?��못된 ?���? (?��메일 ?��?�� ?���?, ?��?�� ?��?�� ?��?��, ?��메일 중복 ?��) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthTokenResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 로그?��?�� ?���? */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description ?���? ?��?�� (리프?��?�� ?��?��?�� ?��?��?���? ?��?��) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 로그?�� ?���? */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthTokenResponse"];
                };
            };
            /** @description ?��못된 ?���? (?��메일 ?��?�� ?���?, ?��?�� ?��?�� ?��?�� ?��) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthTokenResponse"];
                };
            };
            /** @description ?���? ?��?�� (?��메일 ?��?�� 비�?번호 불일�?) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthTokenResponse"];
                };
            };
        };
    };
    getObservationSpots: {
        parameters: {
            query: {
                /** @description �?측�? 조회 ?���? ?���? (?��?��, 경도, 반경) */
                request: components["schemas"]["ObservationSpotRequest"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 ?���? */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ObservationSpotResponse"];
                };
            };
            /** @description ?��못된 ?���? (?��?��/경도 범위 초과, 반경 범위 초과 ?��) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ObservationSpotResponse"][];
                };
            };
        };
    };
    getMyInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 ?���? */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MemberInfoResponse"];
                };
            };
            /** @description ?���? ?��?�� (?��?��?�� ?��?��?���? ?��거나 만료?��) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MemberInfoResponse"];
                };
            };
        };
    };
    validateEmailDuplicated: {
        parameters: {
            query: {
                /**
                 * @description �?증할 ?��메일 주소
                 * @example user@example.com
                 */
                email: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description �?�? ?���? */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MemberValidationResponse"];
                };
            };
            /** @description ?��못된 ?���? (?��메일 ?��?�� ?���? ?��) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MemberValidationResponse"];
                };
            };
        };
    };
    getForecast: {
        parameters: {
            query: {
                /** @description �? �?�? ?���? ?���? ?���? (?��?��, 경도, ?���?, ?���? - ?��짜�? ?��간�? ?��?��?��?��) */
                request: components["schemas"]["StargazingRequest"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 ?���? */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StargazingForecastResponse"];
                };
            };
            /** @description ?��못된 ?���? (?��?��/경도 범위 초과 ?��) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StargazingForecastResponse"];
                };
            };
            /** @description ?���? ?���? (?���? API ?���? ?��?�� ?��) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StargazingForecastResponse"];
                };
            };
        };
    };
    analyzeStargazingCondition: {
        parameters: {
            query: {
                /** @description �? �?�? 조건 분석 ?���? ?���? (?��?��, 경도, ?���?, ?���?) */
                request: components["schemas"]["StargazingRequest"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 분석 ?���? */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StargazingAnalyzeResponse"];
                };
            };
            /** @description ?��못된 ?���? (?��?��/경도 범위 초과, ?���?/?���? ?��?�� ?���? ?��) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StargazingAnalyzeResponse"];
                };
            };
            /** @description ?���? ?���? (?���? API ?���? ?��?�� ?��) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StargazingAnalyzeResponse"];
                };
            };
        };
    };
}
