/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/bookmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBookmarkList"];
        put?: never;
        post: operations["addBookmark"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/reissue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 액세스 토큰 재발급
         * @description 리프레시 토큰을 사용하여 새로운 액세스 토큰을 발급받습니다. 리프레시 토큰은 쿠키에서 자동으로 읽어옵니다.
         */
        post: operations["reissue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 회원가입
         * @description 새로운 회원을 등록합니다. 성공 시 자동으로 로그인되어 JWT 액세스 토큰과 리프레시 토큰(쿠키)을 반환합니다.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그아웃
         * @description 현재 사용자를 로그아웃 처리하고 리프레시 토큰을 무효화합니다. 리프레시 토큰은 쿠키에서 자동으로 읽어옵니다.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그인
         * @description 이메일과 비밀번호로 로그인합니다. 성공 시 JWT 액세스 토큰과 리프레시 토큰(쿠키)을 반환합니다.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 관측지 조회
         * @description 지정된 위치와 반경 내의 별 관측지를 조회합니다. 인증 없이 사용 가능합니다.
         */
        get: operations["getObservationSpots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 정보 조회
         * @description 현재 로그인한 사용자의 정보를 조회합니다. JWT 토큰 인증이 필요합니다.
         */
        get: operations["getMyInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/exists/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 이메일 중복 검증
         * @description 회원가입 시 이메일 중복 여부를 확인합니다. 인증 없이 사용 가능합니다.
         */
        get: operations["validateEmailDuplicated"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 별 관측 예보 조회
         * @description 지정된 위치의 향후 며칠간의 별 관측 예보를 조회합니다. 날짜별, 시간대별로 상세한 관측 조건 점수와 정보를 제공합니다. 인증 없이 사용 가능합니다.
         */
        get: operations["getForecast"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 별 관측 조건 분석
         * @description 지정된 위치, 날짜, 시간의 별 관측 조건을 종합적으로 분석합니다. 기상 정보, 천문 정보, 광해 정보를 포함한 상세 분석 결과를 제공합니다. 인증 없이 사용 가능합니다.
         */
        get: operations["analyzeStargazingCondition"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddBookmarkRequest: {
            /** @enum {string} */
            type: "CUSTOM" | "SPOT";
            /** Format: int64 */
            spotId?: number;
            name: string;
            /** Format: double */
            latitude?: number;
            /** Format: double */
            longitude?: number;
            address?: string;
        };
        BookmarkResponse: {
            /** Format: int64 */
            bookmarkId?: number;
            /** Format: int64 */
            spotId?: number;
            name?: string;
            /** Format: double */
            latitude?: number;
            /** Format: double */
            longitude?: number;
            address?: string;
            type?: string;
        };
        /** @description 인증 토큰 응답 DTO */
        AuthTokenResponse: {
            /**
             * @description JWT 액세스 토큰
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            accessToken?: string;
        };
        /** @description 회원가입 요청 정보 */
        RegisterRequest: {
            /**
             * @description 이메일 주소
             * @example user@example.com
             */
            email: string;
            /**
             * @description 비밀번호 (8자 이상, 영문자/숫자/특수문자(!@#$%^&*) 각각 최소 1개 이상 포함)
             * @example password123!
             */
            password: string;
            /**
             * @description 닉네임
             * @example 별보러가자
             */
            nickname: string;
        };
        /** @description 로그인 요청 정보 */
        LoginRequest: {
            /**
             * @description 이메일 주소
             * @example user@example.com
             */
            email: string;
            /**
             * @description 비밀번호
             * @example password123
             */
            password: string;
        };
        /** @description 관측지 조회 요청 DTO */
        ObservationSpotRequest: {
            /**
             * Format: double
             * @description 위도
             * @example 37.5665
             */
            lat: number;
            /**
             * Format: double
             * @description 경도
             * @example 126.978
             */
            lon: number;
            /**
             * Format: int32
             * @description 검색 반경 (km)
             * @example 50
             */
            radius: number;
        };
        /** @description 관측지 정보 응답 DTO */
        ObservationSpotResponse: {
            /**
             * Format: int64
             * @description 관측지 ID
             * @example 1
             */
            id?: number;
            /**
             * @description 관측지 제목
             * @example 강원도 평창군 대관령
             */
            title?: string;
            /**
             * @description 주소
             * @example 강원도 평창군 대관령면
             */
            address?: string;
            /**
             * Format: double
             * @description 위도
             * @example 37.5665
             */
            latitude?: number;
            /**
             * Format: double
             * @description 경도
             * @example 126.978
             */
            longitude?: number;
            /**
             * @description 관측지 설명
             * @example 별이 잘 보이는 명소입니다.
             */
            description?: string;
            /**
             * Format: int32
             * @description 보틀 등급 (1-9, 낮을수록 좋음)
             * @example 3
             */
            bortleScale?: number;
            /**
             * @description 주차 가능 여부
             * @example true
             */
            isParkingAvailable?: boolean;
            /**
             * @description 화장실 이용 가능 여부
             * @example true
             */
            isRestroomAvailable?: boolean;
            /**
             * @description 차량 접근 가능 여부
             * @example true
             */
            isCarAccess?: boolean;
            /**
             * @description 썸네일 이미지 URL
             * @example https://example.com/image.jpg
             */
            thumbnailImage?: string;
        };
        /** @description 회원 정보 응답 DTO */
        MemberInfoResponse: {
            /**
             * Format: int64
             * @description 회원 ID
             * @example 1
             */
            memberId?: number;
            /**
             * @description 닉네임
             * @example 별보러가자
             */
            nickname?: string;
        };
        /** @description 이메일 중복 검증 응답 DTO */
        MemberValidationResponse: {
            /**
             * @description 검증 결과 (true: 사용 가능, false: 중복됨)
             * @example true
             */
            validated?: boolean;
        };
        /**
         * @description 관측 시간 (HH:mm 형식)
         * @example 22:00
         */
        LocalTime: {
            /** Format: int32 */
            hour?: number;
            /** Format: int32 */
            minute?: number;
            /** Format: int32 */
            second?: number;
            /** Format: int32 */
            nano?: number;
        };
        /** @description 별 관측 조건 분석 요청 DTO */
        StargazingRequest: {
            /**
             * Format: double
             * @description 위도
             * @example 37.5665
             */
            lat: number;
            /**
             * Format: double
             * @description 경도
             * @example 126.978
             */
            lon: number;
            /**
             * Format: date
             * @description 관측 날짜 (yyyy-MM-dd 형식)
             * @example 2025-12-25
             */
            date: string;
            time: components["schemas"]["LocalTime"];
        };
        /** @description 일별 예보 */
        DailyForecast: {
            /**
             * @description 날짜 (요일 포함)
             * @example 2025-05-20 (금)
             */
            date?: string;
            /**
             * @description 일출 시간
             * @example 07:00
             */
            sunrise?: string;
            /**
             * @description 일몰 시간
             * @example 18:00
             */
            sunset?: string;
            /**
             * @description 월출 시간
             * @example 08:00
             */
            moonrise?: string;
            /**
             * @description 월몰 시간
             * @example 20:00
             */
            moonset?: string;
            /** @description 시간대별 예보 목록 */
            hourlyForecasts?: components["schemas"]["HourlyForecast"][];
        };
        /** @description 시간대별 예보 */
        HourlyForecast: {
            /**
             * @description 시간
             * @example 21:00
             */
            time?: string;
            /**
             * Format: int32
             * @description 관측 점수 (0-100)
             * @example 85
             */
            score?: number;
            /**
             * @description 감점 사유 목록
             * @example [
             *       "구름량이 많음"
             *     ]
             */
            reasons?: string[];
            /**
             * @description 별 등급
             * @example 4.5등급
             */
            starGrade?: string;
            /**
             * Format: int32
             * @description 구름량 (%)
             * @example 20
             */
            cloudCover?: number;
            /**
             * @description 달 위상
             * @example 초승달
             */
            moonPhase?: string;
        };
        /** @description 별 관측 예보 응답 DTO */
        StargazingForecastResponse: {
            /** @description 날짜별 예보 목록 */
            dailyForecasts?: components["schemas"]["DailyForecast"][];
        };
        /** @description 천문 정보 */
        AstronomyInfo: {
            /**
             * @description 달 위상
             * @example 초승달
             */
            moonPhase?: string;
            /**
             * @description 일출 시간
             * @example 07:00
             */
            sunrise?: string;
            /**
             * @description 일몰 시간
             * @example 18:00
             */
            sunset?: string;
            /**
             * @description 월출 시간
             * @example 08:00
             */
            moonrise?: string;
            /**
             * @description 월몰 시간
             * @example 20:00
             */
            moonset?: string;
        };
        /** @description 광해 정보 */
        LightPollutionInfo: {
            /**
             * @description 보틀 등급 클래스
             * @example Class 3
             */
            bortleClass?: string;
            /**
             * @description 밝기 수준
             * @example 낮음
             */
            brightness?: string;
            /**
             * @description 한계 등급
             * @example 6등급
             */
            limitingMag?: string;
        };
        /** @description 별 관측 조건 분석 응답 DTO */
        StargazingAnalyzeResponse: {
            /**
             * @description 관측 날짜
             * @example 2025-12-19
             */
            date?: string;
            /**
             * @description 관측 시간
             * @example 22:00
             */
            time?: string;
            /**
             * Format: int32
             * @description 종합 점수 (0-100)
             * @example 85
             */
            totalScore?: number;
            /**
             * @description 점수 감점 사유 목록
             * @example [
             *       "구름량이 많음",
             *       "습도가 높음"
             *     ]
             */
            reasons?: string[];
            /**
             * @description AI 한줄 평
             * @example 오늘 밤 별 관측하기 좋은 날씨입니다!
             */
            aiComment?: string;
            weather?: components["schemas"]["WeatherInfo"];
            astronomy?: components["schemas"]["AstronomyInfo"];
            lightPollution?: components["schemas"]["LightPollutionInfo"];
        };
        /** @description 기상 정보 */
        WeatherInfo: {
            /**
             * Format: int32
             * @description 구름량 (%)
             * @example 20
             */
            cloudIndex?: number;
            /**
             * Format: int32
             * @description 습도 (%)
             * @example 60
             */
            humidityIndex?: number;
            /**
             * @description 가시도 등급
             * @example 매우 좋음
             */
            visibilityText?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getBookmarkList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BookmarkResponse"][];
                };
            };
        };
    };
    addBookmark: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddBookmarkRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BookmarkResponse"];
                };
            };
        };
    };
    reissue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 토큰 재발급 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthTokenResponse"];
                };
            };
            /** @description 인증 실패 (리프레시 토큰이 유효하지 않거나 만료됨) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthTokenResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description 회원가입 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthTokenResponse"];
                };
            };
            /** @description 잘못된 요청 (이메일 형식 오류, 필수 필드 누락, 이메일 중복 등) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthTokenResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 로그아웃 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 인증 실패 (리프레시 토큰이 유효하지 않음) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 로그인 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthTokenResponse"];
                };
            };
            /** @description 잘못된 요청 (이메일 형식 오류, 필수 필드 누락 등) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthTokenResponse"];
                };
            };
            /** @description 인증 실패 (이메일 또는 비밀번호 불일치) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthTokenResponse"];
                };
            };
        };
    };
    getObservationSpots: {
        parameters: {
            query: {
                /** @description 관측지 조회 요청 정보 (위도, 경도, 반경) */
                request: components["schemas"]["ObservationSpotRequest"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ObservationSpotResponse"];
                };
            };
            /** @description 잘못된 요청 (위도/경도 범위 초과, 반경 범위 초과 등) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ObservationSpotResponse"][];
                };
            };
        };
    };
    getMyInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MemberInfoResponse"];
                };
            };
            /** @description 인증 실패 (토큰이 유효하지 않거나 만료됨) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MemberInfoResponse"];
                };
            };
        };
    };
    validateEmailDuplicated: {
        parameters: {
            query: {
                /**
                 * @description 검증할 이메일 주소
                 * @example user@example.com
                 */
                email: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 검증 완료 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MemberValidationResponse"];
                };
            };
            /** @description 잘못된 요청 (이메일 형식 오류 등) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MemberValidationResponse"];
                };
            };
        };
    };
    getForecast: {
        parameters: {
            query: {
                /** @description 별 관측 예보 요청 정보 (위도, 경도, 날짜, 시간 - 날짜와 시간은 선택사항) */
                request: components["schemas"]["StargazingRequest"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StargazingForecastResponse"];
                };
            };
            /** @description 잘못된 요청 (위도/경도 범위 초과 등) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StargazingForecastResponse"];
                };
            };
            /** @description 서버 오류 (외부 API 호출 실패 등) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StargazingForecastResponse"];
                };
            };
        };
    };
    analyzeStargazingCondition: {
        parameters: {
            query: {
                /** @description 별 관측 조건 분석 요청 정보 (위도, 경도, 날짜, 시간) */
                request: components["schemas"]["StargazingRequest"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 분석 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StargazingAnalyzeResponse"];
                };
            };
            /** @description 잘못된 요청 (위도/경도 범위 초과, 날짜/시간 형식 오류 등) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StargazingAnalyzeResponse"];
                };
            };
            /** @description 서버 오류 (외부 API 호출 실패 등) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StargazingAnalyzeResponse"];
                };
            };
        };
    };
}
